DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;

-- delete statuses and todolist
DROP TABLE IF EXISTS todolists CASCADE;
DROP TABLE IF EXISTS statuses CASCADE;
